version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/data:rw
    environment:
      - STATE_DATA_DIR=/data
    restart: unless-stopped
